services:
    dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Service\Dzangocart
        arguments: 
          - %dzangocart.url%
          - %dzangocart.test_code%
          - %dzangocart.secret_key%