parameters:
    DzangocartBundle.controller.order.class: Dzangocart\Bundle\DzangocartBundle\Controller\OrderController

services:
    dzangocart:
        class:          Dzangocart\Client\DzangocartClient
        factory_class:  Dzangocart\Client\DzangocartClient
        factory_method: factory
        arguments:      ["%dzangocart.config%"]

    twig.extension.dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Twig\Extension\DzangocartExtension
        arguments: [@dzangocart]
        tags:
            - { name: twig.extension }

    DzangocartBundle.order.controller:
        class:      "%DzangocartBundle.controller.order.class%"
        arguments:  [@service_container]
