parameters:
    dzangocart.controller.catalogue.class: Dzangocart\Bundle\DzangocartBundle\Controller\CatalogueController
    dzangocart.controller.order.class: Dzangocart\Bundle\DzangocartBundle\Controller\OrderController
    dzangocart.controller.sale.class: Dzangocart\Bundle\DzangocartBundle\Controller\SaleController

services:
    dzangocart:
        class:          Dzangocart\Client\DzangocartClient
        factory_class:  Dzangocart\Client\DzangocartClient
        factory_method: factory
        arguments:      ["%dzangocart.config%"]

    twig.extension.dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Twig\Extension\DzangocartExtension
        arguments: [@dzangocart]
        tags:
            - { name: twig.extension }

    dzangocart.controller.catalogue:
        class:      "%dzangocart.controller.catalogue.class%"
        arguments:
            - @dzangocart
            - @form.factory

    dzangocart.controller.order:
        class:      "%dzangocart.controller.order.class%"
        arguments:
            - @dzangocart
            - "%dzangocart.config%"
            - @form.factory

    dzangocart.controller.sale:
        class:      "%dzangocart.controller.sale.class%"
        arguments:
            - @dzangocart
            - "%dzangocart.config%"
            - @form.factory
