services:
    dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Service\Dzangocart
        arguments: 
          - %dzangocart.url%
          - %dzangocart.test_code%
          - %dzangocart.secret_key%        
        calls:
            - [ setAddToCartLabel, [ %dzangocart.add_to_cart.label% ] ]
            - [ setAddToCartTitle, [ %dzangocart.add_to_cart.title% ] ]
          
    twig.extension.dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Twig\Extension\DzangocartExtension
        arguments:    
          - "@service_container"
          - "@dzangocart"
        tags:
            - { name: twig.extension }