services:
    dzangocart:
        class:          Dzangocart\Client\DzangocartClient
        factory_class:  Dzangocart\Client\DzangocartClient
        factory_method: factory
        arguments:      ["%dzangocart.config%"]

    twig.extension.dzangocart:
        class: Dzangocart\Bundle\DzangocartBundle\Twig\Extension\DzangocartExtension
        arguments: ["@dzangocart"]
        tags:
            - { name: twig.extension }
