_dzangocart_admin_order:
    resource: "@DzangocartBundle/Resources/config/routing/order.yml"

dzangocart_admin_sale:
    resource: "@DzangocartBundle/Resources/config/routing/sale.yml"

dzangocart_admin_catalogue:
    resource: "@DzangocartBundle/Resources/config/routing/catalogue.yml"

dzangocart_admin_payment:
    resource: "@DzangocartBundle/Resources/config/routing/direct_payment.yml"
