dzangocart_catalogue:
    pattern: /catalogue
    defaults: { _controller: dzangocart.controller.catalogue:indexAction }

dzangocart_category:
    pattern: /catalogue/category/{id}
    defaults: { _controller: dzangocart.controller.catalogue:showAction }
    requirements:
        id: \d+

dzangocart_category_update:
    pattern: /catalogue/category/{id}/update
    defaults: { _controller: dzangocart.controller.catalogue:updateAction }
    methods:  [GET, POST]
    requirements:
        id: \d+
