dzangocart_orders:
    pattern: /order
    defaults: { _controller: dzangocart.controller.order:indexAction }

dzangocart_orders_list:
    pattern: /order/list
    defaults: { _controller: dzangocart.controller.order:listAction, _format: json }
    requirements:
        _format: json
