dzangocart_orders:
    pattern: /order
    defaults: { _controller: DzangocartBundle.order.controller:indexAction }
    
dzangocart_orders_list:
    pattern: /order/list
    defaults: { _controller: DzangocartBundle.order.controller:listAction, _format: json }
    requirements:
        _format: json
