dzangocart_orders:
    pattern: /order
    defaults:
        _controller: DzangocartBundle:Order:index

dzangocart_order:
    pattern: /order/{id}
    defaults:
        _controller: DzangocartBundle:Order:show
    requirements:
        id: \d+

dzangocart_orders_list:
    pattern: /order/list
    defaults:
        _controller: DzangocartBundle:Order:list
        _format: json
    requirements:
        _format: json

dzangocart_customer_search:
    pattern: /search/{search}
    defaults:
        _controller: DzangocartBundle:Order:search
        _format: json
    requirements:
        _format: json
