dzangocart_sales:
    pattern: /sale
    defaults:
        _controller: DzangocartBundle:Sale:index

dzangocart_sale:
    pattern: /sale/{id}
    defaults:
        _controller: DzangocartBundle:Sale:show
    requirements:
        id: \d+

dzangocart_sale_list:
    pattern: /sale/list
    defaults:
        _controller: DzangocartBundle:Sale:list
        _format: json
    requirements:
        _format: json
